name: Daily Homework Check
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up German Locale
        run: |
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium
        
      - name: Run Script
        env:
          UNTIS_SERVER: ${{ secrets.UNTIS_SERVER }}
          UNTIS_SCHOOL: ${{ secrets.UNTIS_SCHOOL }}
          UNTIS_USER: ${{ secrets.UNTIS_USER }}
          UNTIS_PASSWORD: ${{ secrets.UNTIS_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_CC: ${{ secrets.EMAIL_CC }}
        run: python homework_scraper.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
